config/routes.rb
Rails.application.routes.draw do

  # resources :comments
  # resources :posts
  # resources :records
  resources :records do
    collection do
      get :thirty_days
      get :sixty_days
    end
  end
  devise_for :users
  get "u/:username", to: "public#profile", constraints: { username: /[^\/]+/}, as: "profile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "search", to: "records#search", as: "search"
  # get "business", to: "records#business", as: "business"

  get "terms", to: "records#terms", as: "terms"
  get "privacy", to: "records#privacy", as: "privacy"
  get "websiteprivacypage", to: "records#websiteprivacy", as: "websiteprivacy"
  get "home", to: "records#home", as: "home"
  get "vaccines", to: "records#vaccines", as: "vaccines"

  delete 'records/:id/picture', to: 'records#destroy_picture', as: 'picdestroy'

  get "users", to: "users#index", as:"users"
  get "business", to: "records#business", as: "business"


  resources :communities do
    resources :posts
  end



  resources :subscriptions
  resources :comments, only: [:create]
  post "post/vote", to: "votes#create"
  post "comment/votecomment", to: "votecomments#create"




  # authenticated :user do
  #   root 'records#new', as: :authenticated_poop
  # end
  authenticated :user do
    root :to => 'records#routes'
  end
  root to: 'records#home'
  # root to: 'records#home'
  get "public", to: "public#index", as: "public"
end

app/models/record.rb
class Record < ApplicationRecord
  validates :date, presence: true
  validates :name, presence: true
  mount_uploader :photo, PhotoUploader


  belongs_to :user
  has_many :record_prescriptions, dependent: :destroy
  has_many :prescriptions, through: :record_prescriptions
  has_many :record_tests, dependent: :destroy
  has_many :tests, through: :record_tests
  has_many :record_prescription_types, dependent: :destroy
  has_many :prescriptiontypes, through: :record_prescription_types

  has_many :record_xrays, dependent: :destroy
  has_many :xrays, through: :record_xrays

  include PgSearch
  pg_search_scope :search_by_name,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    pg_search_scope :search_by_description,
    against: [ :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
    pg_search_scope :search_by_description_other,
    against: [ :description_other ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    pg_search_scope :search_by_name_other,
    against: [ :name_other ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

     pg_search_scope :search_by_prescription_name,
    against: [ :prescription_name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    pg_search_scope :search_by_name_and_description,
    against: [ :name, :description],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    pg_search_scope :search_by_name_and_description_other,
    against: [ :name_other, :description_other],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin, only: :business
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => [:home, :terms, :privacy, :websiteprivacy]

  # GET /records
  # GET /records.json
  def index
    @recordsUser = current_user.records
    @records = @recordsUser.order(:date)
     if @records
    respond_to do |format|
        format.html
        format.js
    end
  end


  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])
    @date = @record.date
    @prescription_names = []
     @record.prescriptions.each do |x|
      @prescription_names << x.name
    end
    @tests = []
    @record.tests.each do |x|
      @tests << x.name
    end
    @xray_name = []
    @record.xrays.each do |x|
      @xray_name << x.name
    end
    if @record.photo.url
      unsecure = @record.photo.url
      @secure = @record.photo.url.gsub('http','https')
    end
  end

def destroy_picture
 @record = Record.find(params[:id])
  @record.remove_photo!
  @record.save!
  redirect_to @record
end
  # GET /records/new
  def new
    @user = current_user
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @user = User.find(current_user.id)
    @record = Record.new(record_params)
    @record.user = @user

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, success: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end


  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, info: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, danger: 'Record was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:query].present? && params[:query2].present? == false && params[:query3].present? == false
      @record = current_user.records
      @records = @record.search_by_name(params[:query])
      @record_name_other = @record.search_by_name_other(params[:query])


    elsif params[:query3].present? == true && params[:query2].present? == true && params[:query].present? == false
    @record = current_user.records
    @record_description = @record.search_by_description(params[:query3])
    @record_description_custom = @record.search_by_description_other(params[:query3])
    @record_prescription_name = @record.search_by_prescription_name(params[:query2])
    @records = []
    if @record_description
      @record_description.each do |record|
        @record_prescription_name.each do |pres|
          if pres == record
            @records << record
          end
        end
      end
    end

    if @record_description_custom
      @record_description_custom.each do |record|
        @record_prescription_name.each do |pres|
          if pres == record
            @records << record
          end
        end
      end
    end


    elsif params[:query2].present? && params[:query].present? == false && params[:query].present? == false
      @record = current_user.records
      @records = @record.search_by_prescription_name(params[:query2])



  elsif params[:query3].present? && params[:query].present? == false && params[:query2].present? == false
    @records = []
    @record = current_user.records
    @records = @record.search_by_description(params[:query3])
    @record_description_other = @record.search_by_description_other(params[:query3])


elsif params[:query].present? && params[:query3].present? && params[:query2].present? == false
      @recor = current_user.records
      @record_name = @recor.search_by_name_and_description(params[:query])
      @record_name_new_other = @recor.search_by_name_and_description_other(params[:query])
      @record_description = @recor.search_by_name_and_description(params[:query3])
      @record_description_new_other = @recor.search_by_name_and_description_other(params[:query3])
      @records = []
       if @record_name
        if @record_description
          @record_name.each do |record|
            @record_description.each do |desc|
              if record == desc
                @records << record
            end
          end
        end
        end
      end

      if @record_name
        if @record_description_new_other
          @record_name.each do |record|
            @record_description_new_other.each do |desc|
              if record == desc
                @records << record
          end
        end
      end
    end
  end

      if @record_name_new_other
        if @record_description
          @record_name_new_other.each do |record|
            @record_description.each do |desc|
              if record == desc
                @records << record
            end
          end
        end
      end
    end

    if @record_name_new_other
        if @record_description_new_other
          @record_name_new_other.each do |record|
            @record_description_new_other.each do |desc|
              if record == desc
                @records << record
            end
          end
        end
      end
    end

  elsif params[:query].present? && params[:query2].present? && params[:query3].present? == false
    @record = current_user.records
    @record_reason = @record.search_by_name(params[:query])
    @record_reason_other = @record.search_by_name_other(params[:query])
    @record_prescription_name = @record.search_by_prescription_name(params[:query2])
    @records = []

    if @record_reason
    @record_reason.each do |record|
      @record_prescription_name.each do |pres|
        if record == pres
          @records << record
        end
      end
    end
  end

  if @record_reason_other
    @record_reason_other.each do |record|
      @record_prescription_name.each do |pres|
        if record == pres
          @records << record
        end
      end
    end
  end

elsif params[:query].present? &&  params[:query3].present? && params[:query2].present?
    @record = current_user.records

    @record_reason = @record.search_by_name(params[:query])
    @record_reason_other = @record.search_by_name_other(params[:query])

    @record_description = @record.search_by_name_and_description(params[:query3])
    @record_description_new_other = @record.search_by_name_and_description_other(params[:query3])

    @record_prescription_name = @record.search_by_prescription_name(params[:query2])

    @records = []

    if @record_reason
      if @record_description
        @record_reason.each do |record|
          @record_description.each do |desc|
            @record_prescription_name.each do |pres|
              if record == desc && record == pres
                @records << record
              end
            end
          end
        end
      end
    end



    if @record_reason
      if @record_description_new_other
        @record_reason.each do |record|
          @record_description_new_other.each do |desc|
            @record_prescription_name.each do |pres|
              if record == desc && record == pres
                @records << record
              end
            end
          end
        end
      end
    end


    if @record_reason_other
      if @record_description
        @record_reason_other.each do |record|
          @record_description.each do |desc|
            @record_prescription_name.each do |pres|
              if record == desc && record == pres
                @records << record
              end
            end
          end
        end
      end
    end


    if @record_reason_other
      if @record_description_new_other
        @record_reason_other.each do |record|
          @record_description_new_other.each do |desc|
            @record_prescription_name.each do |pres|
              if record == desc && record == pres
                @records << record
              end
            end
          end
        end
      end
    end

    end
  end


  def thirty_days
    @userrecords = current_user.records
    @recordsSort = @userrecords.where('date > ?', 30.days.ago)

    @records = @recordsSort.order(:date)

    respond_to do |format|
      format.html
      format.js {render layout: false} # Add this line to you respond_to block
    end

  end



  def sixty_days
    @userrecords = current_user.records
    @records = @userrecords.where('date > ?', 60.days.ago)

    @records = @recordsSort.order(:date)

    respond_to do |format|
      format.html
      format.js {render layout: false} # Add this line to you respond_to block
    end
  end

def vaccines
    @userrecords = current_user.records
    @records = []
    @userrecords.each do |record|
      if record.name == "Vaccine"
         @records << record
       end
    end
    respond_to do |format|
      format.html
      format.js {render layout: false} # Add this line to you respond_to block
    end
  end


  def business
    # @records = Record.all
    # @ct = state_records("CT")
    # @ct_record_reason = record_reason(@ct)
    # @ct_record_array_reason_other = record_reason_other(@ct)
    # @ct_record_test = record_test(@ct)
    # @ct_record_test_other = record_test_other(@ct)


    # @TX = state_records('TX')
    # @TX_record_reason = record_reason(@TX)

app/views/records/_form.html.erb
<div class = "form"> <%= simple_form_for(@record) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :date, as: :string, input_html: { class: "datepicker"}, label: "Date" %>







    <%= f.label :name, label: "Reason" %><br>

  <%= f.select(:name, [['Vaccine', 'Vaccine'],['Regular Checkup', 'Regular Checkup'], ['Cold', 'Cold'], ['Skin Disorder', 'Skin Disorder'], ['Joint Pain', 'Joint Pain'], ['Cholesterol Problems','Cholesterol Problems'],['High Blood Pressure','High Blood Pressure'],['Other', 'Other']], {:prompt => "Choose One"}, {class: "form-control", id: "Reason_description"}) %>
  <br>

<div id="otherReason">
    <%= f.text_field :name_other, class: "form-control" %>
  </div>
 <%= f.select(:vaccine, [['Moderna 1 (COVID-19)','Moderna 1 (COVID-19)'], ['Moderna 2 (COVID-19)', 'Moderna 2 (COVID-19)'], ['Pfizer 1 (COVID-19)', 'Pfizer 1 (COVID-19)'], ['Pfizer 2 (COVID-19)', 'Pfizer 2 (COVID-19)'], ['Johnson & Johnson (COVID-19)', 'Johnson & Johnson (COVID-19)'],['Vaccinia (smallpox)', 'Vaccinia (smallpox)'],['Measles, mumps, rubella (MMR combined vaccine)', 'Measles, mumps, rubella (MMR combined vaccine)'], ['Varicella (chickenpox)', 'Varicella (chickenpox)'], ['Influenza (nasal spray)', 'Influenza (nasal spray)'], ['Rotavirus', 'Rotavirus'], ['Zoster (shingles)','Zoster (shingles)'],['Yellow fever','Yellow fever'],['Other', 'Other']], {:prompt => "Choose One"}, {class: "form-control", id: "vaccine_description"}) %>

  <div id="otherVaccine">
    <%= f.text_field :vaccine_other, class: "form-control" %>
  </div>
  <div class = "optionalInfo"> <strong> Optional Info: </strong> </div>
  <%= f.input :photo, label: "Receipt(s) Upload:" %>
  <%= f.input :photo_cache, as: :hidden %>

    <%= f.input :doctor, label: "Doctor name" %>

    <strong> <%= f.label "Prescription" %> </strong> <br />
    <%= f.collection_check_boxes :prescription_ids, Prescription.all, :id, :name do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
      <% end %>

    <%= f.input :prescription_name, label: "Prescription name" %>

    <strong> <%= f.label "Xray Done?" %> </strong> <br />
    <%= f.collection_check_boxes :xray_ids, Xray.all, :id, :name do |b| %>
      <div class="collection-check-box">
       <%= b.check_box %>
        <%= b.label %>
      </div>
      <% end %>

      <strong> <%= f.label "Test Done?" %> </strong> <br />
    <%= f.collection_check_boxes :test_ids, Test.all, :id, :name do |b| %>
      <div class="collection-check-box">
       <%= b.check_box %>
        <%= b.label %>
      </div>
      <% end %>


 <%= f.label :description, "If Yes, Choose Test Type" %><br>

  <%= f.select(:description, [['None', 'None'], ['Blood Test', 'Blood Test'], ['Echocardiography', 'Echocardiography'], ['Colonoscopy', 'Colonoscopy'], ['Other', 'Other']], {}, {class: "form-control", id: "expense_description"}) %>
  <br>
  <div id="otherDesc">
    <%= f.text_field :description_other, class: "form-control" %>
  </div>

  <%= f.label :rating, "Doctor Rating" %><br>

   <%= f.select(:rating, [['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5']], {:prompt => "Choose One"}, {class: "form-control"}) %>
   <br>
<%= f.input :comment, label: "Comments:" %>
<br>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary', id: 'sweet-alert-demo' %>
  </div>
<% end %>

</div>

app/views/records/_formedit.html.erb
<div class = "form"> <%= simple_form_for(@record) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :date, as: :string, input_html: { class: "datepicker"}, label: "Date" %>


    <%= f.label :name, label: "Reason" %><br>

  <%= f.select(:name, [['Vaccine', 'Vaccine'],['Regular Checkup', 'Regular Checkup'], ['Cold', 'Cold'], ['Skin Disorder', 'Skin Disorder'], ['Joint Pain', 'Joint Pain'], ['Cholesterol Problems','Cholesterol Problems'],['High Blood Pressure','High Blood Pressure'],['Other', 'Other']], {:prompt => "Choose One"}, {class: "form-control", id: "reasonedit_description"}) %>
  <br>

<div id="otherReasonedit">
    <%= f.text_field :name_other, class: "form-control" %>
  </div>


  <%= f.select(:vaccine, [ ['Moderna 1 (COVID-19)','Moderna 1 (COVID-19)'], ['Moderna 2 (COVID-19)', 'Moderna 2 (COVID-19)'], ['Pfizer 1 (COVID-19)', 'Pfizer 1 (COVID-19)'], ['Pfizer 2 (COVID-19)', 'Pfizer 2 (COVID-19)'], ['Johnson & Johnson (COVID-19)', 'Johnson & Johnson (COVID-19)'],['Vaccinia (smallpox)', 'Vaccinia (smallpox)'],['Measles, mumps, rubella (MMR combined vaccine)', 'Measles, mumps, rubella (MMR combined vaccine)'], ['Varicella (chickenpox)', 'Varicella (chickenpox)'], ['Influenza (nasal spray)', 'Influenza (nasal spray)'], ['Rotavirus', 'Rotavirus'], ['Zoster (shingles)','Zoster (shingles)'],['Yellow fever','Yellow fever'],['Other', 'Other']], {:prompt => "Choose One"}, {class: "form-control", id: "vaccineedit_description"}) %>
  <br>
    <div id="otherVaccine">
    <%= f.text_field :vaccine_other, class: "form-control" %>
  </div>

  <div class = "optionalInfo"> <strong> Optional Info: </strong> </div>
  <%= f.input :photo, label: "Receipt(s) Upload:" %>
 <%= f.input :photo_cache, as: :hidden %>

  <%= f.input :doctor, label: "Doctor name" %>

    <strong> <%= f.label "Prescription" %> </strong> <br />
    <%= f.collection_check_boxes :prescription_ids, Prescription.all, :id, :name do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
      <% end %>

      <%= f.input :prescription_name, label: "Prescription name" %>

      <strong> <%= f.label "Xray Done?" %> </strong> <br />
    <%= f.collection_check_boxes :xray_ids, Xray.all, :id, :name do |b| %>
      <div class="collection-check-box">
       <%= b.check_box %>
        <%= b.label %>
      </div>
      <% end %>

      <strong> <%= f.label "Test Done?" %> </strong> <br />
    <%= f.collection_check_boxes :test_ids, Test.all, :id, :name do |b| %>
      <div class="collection-check-box">
       <%= b.check_box %>
        <%= b.label %>
      </div>
      <% end %>

 <%= f.label :description, "If Yes, Choose Test Type" %><br>

  <%= f.select(:description, [['None', 'None'], ['Blood Test', 'Blood Test'], ['Echocardiography', 'Echocardiography'], ['Colonoscopy', 'Colonoscopy'], ['Other', 'Other']], {}, {class: "form-control", id: "expens_description"}) %>
  <br>
  <div id="otherDes">
    <%= f.text_field :description_other, class: "form-control" %>
  </div>

<%= f.label :rating, "Doctor Rating" %><br>

   <%= f.select(:rating, [['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5']], { :prompt => "Choose One"}, {class: "form-control"}) %>
   <br>
<%= f.input :comment, label: "Comments:" %>
<br>





  </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary updateButton', id: 'sweet-alert-edit' %>
  </div>
<% end %>

</div>

app/views/records/business.html.erb
<p> </p>
<%=
  link_to 'Download Data as an Excel File ',
  business_path(format: :xlsx)
%>

app/views/records/index.html.erb
<div class="container">

  <% flash.each do |key, value| %>
    <% if key == "danger" %>
    <div class="alert alert-<%= key %>"><%= value %></div>
     <% end %>
  <% end %>
  <%= yield %>
</div>

<h1 class = "recordtitle indextitle"> Records</h1>

<div class = "days"> <%= link_to "All Records", records_path, class: "showbutton", remote: true %>

<%= link_to "Last Thirty days", thirty_days_records_path, class: "showbutton", remote: true %>
<%= link_to "Last Sixty days", sixty_days_records_path, class: "showbutton", remote: true %> </div>

<%= render 'index', records: @records %>


<div id = "current_customer">
</div>

app/views/records/index.js.erb
$("#current_customer").html("<%= escape_javascript(render partial: 'index', locals: { records: @records } ) %>");

app/views/records/search.html.erb
 <h3 class = "recordtitle"> Search for record(s) using one or more field(s) </h3>
<div class="wrapper">
  <div class="row row-banner">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 search-container">
      <div class="logo-and-search">
  <%= image_tag("", id: "logo") %>


          <h5 class = "search">Reason</h5>
        <%= form_tag search_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control search-item searchheight",
          placeholder: "Joint Pain"
          %> <br>

          <h5 > Test type?</h5>
          <%= text_field_tag :query3,
          params[:query3],
          class: "form-control search-item searchheight",
            placeholder: "Blood test",
            id: "address-input"
            %>
              <br>

           <h5 > Prescription name?</h5>
          <%= text_field_tag :query2,
          params[:query2],
          class: "form-control search-item searchheight",
            placeholder: "Retinol",
            id: "address-input"
            %>
              <br>





            <%= submit_tag("Search", :id=>"button", :class=>"btn btn-secondary btn-lg btn-main btn btn-default", :name=>"submit") %>
            <% end %>
          </div>

        </div>
      </div>
    </div>
    <br>

    <%= link_to "Show All Vaccine Records", vaccines_path, class: "showbutton vaccinesmargin", remote: true %>

    <div id = "current_customer">
  </div>

  <%if @records %>
    <div class="container">
      <div class="row">
        <% @records.each do |record| %>
           <div class="col-xs-12 col-sm-4">
      <!-- insert <div class="card"> -->
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">

        <div class="card-description">
       <a href= "#" class="links"><%=(record.name == "Other" ? record.name_other : record.name) %></a>
       <h5 class = "recorddetails"> Press for record details </h5>
      </div>
      <a class="card-link" href= <%=record_path(record.id) %> ></a>
    </div>

    <div class="card-footer editfooter">
      <span class= "edit"> <small class="text-muted">  <%= link_to "Edit record", edit_record_path(record.id) %>  </small> </span>
    </div>

     <div class="card-footer deletefooter">
      <span class= "delete"> <small class="text-muted">  <%= link_to "Delete record", record_path(record.id), method: :delete %>  </small> </span>
    </div>

  </div>
  <% end %>
   </div>

</div>
<% end %>



<%if @record_name_other %>
    <div class="container">
  <div class="row">
<% @record_name_other.each do |record| %>

  <div class="col-xs-12 col-sm-4">
      <!-- insert <div class="card"> -->
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">

        <div class="card-description">
       <a href= "#" class="links"><%=(record.name == "Other" ? record.name_other : record.name) %></a>
       <h5 class = "recorddetails"> Press for record details </h5>
      </div>
      <a class="card-link" href= <%=record_path(record.id) %> ></a>
    </div>

    <div class="card-footer editfooter">
      <span class= "edit"> <small class="text-muted">  <%= link_to "Edit record", edit_record_path(record.id) %>  </small> </span>
    </div>

     <div class="card-footer deletefooter">
      <span class= "delete"> <small class="text-muted">  <%= link_to "Delete record", record_path(record.id), method: :delete, id: "delete-link", :data => {:confirm => 'Are you sure?'} %>  </small> </span>
    </div>

  </div>
  <% end %>
   </div>

</div>
<% end %>



<%if @record_description_other %>
    <div class="container">
  <div class="row">
<% @record_description_other.each do |record| %>

  <div class="col-xs-12 col-sm-4">
      <!-- insert <div class="card"> -->
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">

        <div class="card-description">
       <a href= "#" class="links"><%=(record.name == "Other" ? record.name_other : record.name) %></a>
       <h5 class = "recorddetails"> Press for record details </h5>
      </div>
      <a class="card-link" href= <%=record_path(record.id) %> ></a>
    </div>

    <div class="card-footer editfooter">
      <span class= "edit"> <small class="text-muted">  <%= link_to "Edit record", edit_record_path(record.id) %>  </small> </span>
    </div>

     <div class="card-footer deletefooter">
      <span class= "delete"> <small class="text-muted">  <%= link_to "Delete record", record_path(record.id), method: :delete, id: "delete-link", :data => {:confirm => 'Are you sure?'} %>  </small> </span>
    </div>

  </div>
  <% end %>
   </div>

</div>
<% end %>

app/views/records/show.html.erb
<div class="container">

  <% flash.each do |key, value| %>
    <% if key == "success" %>
    <div class="alert alert-<%= key %>"><%= value %></div>
     <% end %>
  <% end %>
  <%= yield %>
</div>
<div class="container">
<% flash.each do |key, value| %>
    <% if key == "info" %>
    <div class="alert alert-<%= key %>"><%= value %></div>
     <% end %>
  <% end %>
  <%= yield %>
</div>


<div class = "showform"
<p> Date: <strong> <%= @date.strftime("%B %d, %Y") %> </strong> </p>

<p>
  Reason:
  <strong> <%= @record.name == "Other" ? @record.name_other : @record.name %> </strong>
</p>

<% if @record.name == "Vaccine" %>
<p>
  Vaccine type:
  <strong> <%= @record.vaccine == "Other" ? @record.vaccine_other : @record.vaccine %> </strong>
</p>
<% end %>

<p> Doctor: <strong> <%= @record.doctor %> </strong> </p>
  <p> Were you given a prescription? <strong> <%= @prescription_names.to_sentence %> </strong>
</p>
<p> Prescription type: <strong> <%=@record.prescription_name %> </strong> </p>

 <p> Xray? <strong> <%= @xray_name.to_sentence %> </strong> </p>

<p> Test Done? <strong> <%= @tests.to_sentence %> </strong> </p>


  <% if  @record.description == "Other"%>
    <p> Test type: <strong> <%= @record.description_other %> </strong> </p>
  <% elsif  @record.description == "None"%>
    <p> Test type:  </p>
  <% else %>
    <p> Test type: <strong> <%= @record.description %> </strong> </p>
  <% end %>


<p> Doctor Rating: <strong> <%= @record.rating %></strong> </p>

<p> Comments: <strong> <%= @record.comment %> </strong> </p>
<p> Photo:
  <% if @record.photo? %>
  <li class="thumbnail col-xs-2">
        <%= link_to @secure, class: :popup_link, target: :_blank do %>
         <%= image_tag @secure, class: "imagesrc"  %>
       <% end %>
     </li>
     <% end %>
   </p>
   <% if @record.photo? %>
   <span class = "viewphoto"> (Click to view) </span>
   <% end %>
<br>

<% if @record.photo? %>
<%= link_to picdestroy_path(@record), method: :delete do %>
  <i class="fa fa-trash deleteicon" aria-hidden="true"></i> (Delete)
<% end %>
<% end %>



<div class = "movebuttons">
<div> <%= link_to 'Edit', edit_record_path(@record), class: "showbutton" %> |
<%= link_to 'All Records', records_path, class: "showbutton" %> </div>
<br>

 <div> <%= link_to 'Search for record(s)', search_path, class: "showbutton" %> </div>
</div>

 <!-- comment -->
 <% if false %>
<%  @prescription_names.each do |x| %>
  <%= x %>
  <% end %>
<% end %>

</div>