config/routes.rb
Rails.application.routes.draw do

  # resources :comments
  # resources :posts
  # resources :records
  resources :records do
    collection do
      get :thirty_days
      get :sixty_days
    end
  end
  devise_for :users
  get "u/:username", to: "public#profile", constraints: { username: /[^\/]+/}, as: "profile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "search", to: "records#search", as: "search"
  # get "business", to: "records#business", as: "business"

  get "terms", to: "records#terms", as: "terms"
  get "privacy", to: "records#privacy", as: "privacy"
  get "websiteprivacypage", to: "records#websiteprivacy", as: "websiteprivacy"
  get "home", to: "records#home", as: "home"
  get "vaccines", to: "records#vaccines", as: "vaccines"

  delete 'records/:id/picture', to: 'records#destroy_picture', as: 'picdestroy'

  get "users", to: "users#index", as:"users"
  get "business", to: "records#business", as: "business"


  resources :communities do
    resources :posts
  end



  resources :subscriptions
  resources :comments, only: [:create]
  post "post/vote", to: "votes#create"
  post "comment/votecomment", to: "votecomments#create"




  # authenticated :user do
  #   root 'records#new', as: :authenticated_poop
  # end
  authenticated :user do
    root :to => 'records#routes'
  end
  root to: 'records#home'
  # root to: 'records#home'
  get "public", to: "public#index", as: "public"
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :community
    has_many :comments
    has_many :votes
    validates_presence_of :title, :body, :user_id, :community_id

    # def self.post_order
    #     posts = Post.all
    #     posts.sort_by{ |p| p.score }.reverse
    # end

    def score
        if self.upvotes > 0 || self.downvotes > 0
            self.upvotes > 0 ? (self.upvotes - self.downvotes) : (self.downvotes * -1)
        else
            0
        end
    end

    def total_comments
        if self.comments
            self.comments.count
        else
            0
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [ :index, :show ]
    before_action :set_posts, only: [ :show ]
    before_action :auth_subscriber, only: [ :new ]

        def index
            @posts = Post.all
        end

        def show
            @comment = Comment.new
        end

        def new
            @community = Community.find(params[:community_id])
            @post = Post.new
        end

        def create
            @post = Post.new(post_params)

            @post.user_id= current_user.id
            @post.community_id = params[:community_id]
            if @post.save
                redirect_to community_path(@post.community_id)
            else
                @community = Community.find(params[:community_id])
                render :new
            end
        end


      # def destroy
      #   @post.destroy
      #   respond_to do |format|
      #     format.html { redirect_to records_url, danger: 'Post was successfully deleted.' }
      #     format.json { head :no_content }
      #   end
      # end

        private

        def set_posts
            @post = Post.includes(:comments).find(params[:id])
            @postcomments = @post.comments.sort_by{ |p| p.score }.reverse
        end

        # refactor scope method, place it in Post model or Subscription model?
        def auth_subscriber
        # #    unless Subscription.check_if_account_signed_in(community.id = params[:community_id], current_account)
        # #     redirect_to root_path, flash: { error: "You are not authorized to view this page" }
        # #    end
        unless Subscription.where(community_id: params[:community_id], user_id: current_user.id).any?
            redirect_to root_path, flash: {error: "You do not have authorization to access this page"}
        end
        end

        def post_params
            params.require(:post).permit(:title, :body)
        end
    end

app/views/posts/_comments.html.erb
<% if comments.any? %>
<% comments.each do |comment| %>
<div class="comment">
    <%= link_to comment.user.username, profile_path(comment.user.username)%>:
    <%= simple_format comment.message %>
    <div id="vote-actionscomments-<%= comment.id %>" class="votecomment horizontal" data-id="<%= comment.id %>">
                    <div class="fa fa-arrow-up upvote horiz <%= is_upvoted comment %>"></div>
                    <span class="font-weight-bold score horiz2"><%= comment.score %></span>
                    <div class="fa fa-arrow-down downvote horiz3 <%= is_downvoted comment %>"></div>
                </div>

</div>
<% end %>
<% end %>

app/views/posts/_form.html.erb
<div class="row1">
    <div class="col-sm-6">
        <%= form_for [@community, @post] do |form| %>
            <div class="form-group">
                <%= label_tag :title %>
                <%= form.text_field :title, class: "form-control"%>
            </div>

            <div class="form-group">
                <%= label_tag :body %>
                <%= form.text_area :body, :cols => 80, :rows => 4, class: "form-control"%>
            </div>

            <%= form.submit "Submit", class:"btn btn-primary"%>
        <% end %>
    </div>
</div>

app/views/posts/_list.html.erb
<% posts.each do |post| %>

<div class="card-trip">

  <div class="card-trip-infos">
    <div id="vote-actions-<%= post.id %>" class="vote" data-id="<%= post.id %>">
                    <div class="fa fa-arrow-up upvote  <%= is_upvoted post %>"></div>
                    <span class="font-weight-bold score"><%= post.score %></span>
                    <div class="fa fa-arrow-down downvote  <%= is_downvoted post %>"></div>
                </div>
    <div>
        <div class="col-11">
                <h4 class="mb-1"><%= link_to post.title, community_post_path(post.community_id, post) %></h4>
                <p><small><%= link_to post.community.name, community_path(post.community) %> Posted by <%= link_to post.user.username, profile_path(post.user.username) %> <%= time_ago_in_words post.created_at %> ago.</small></p>
                <p><%= truncate post.body, length: 200 %></p>
                <p><%= post.total_comments %> Comments</p>
            </div>
    </div>


  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<h2> Edit Post </h2>

<%= render partial: "form" %>

app/views/posts/new.html.erb
<h2 class= "newleft"> New Post </h2>

<%= render partial: "layouts/errors", locals: {object: @post} %>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<div class="card-trip1">

<div class="row1">
    <div class="col-1 text-center">

        </div>
    <div class="col-11">

        <h2 class = "posttitle"><%= @post.title %></h2>

    <%= simple_format @post.body %>

    <div id="post-comments">
        <h5>Comment as <%= link_to current_user.username, profile_path(current_user.username) %></h5>
        <%= form_for @comment, remote: true do |f| %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_area :message, placeholder: "Your comment goes here", class: "form-control" %>
            <%= f.submit "Submit comment", class: "btn btn-success mt-3 mb-3 commentbuttondown"%>
        <% end %>
        <br> <%= render partial: "posts/comments", locals: { comments: @postcomments } %>
    </div>
    </div>
</div>

</div>

<div class = "newleft"><%= link_to "View This Community's Posts", community_path(@post.community_id), class: "btn btn-primary mt-4"%> </div>

<div class = "newleft poppadding"><%= link_to "Popular Posts", public_path, class: "btn btn-primary mt-4"%> </div>