config/routes.rb
Rails.application.routes.draw do

  # resources :comments
  # resources :posts
  # resources :records
  resources :records do
    collection do
      get :thirty_days
      get :sixty_days
    end
  end
  devise_for :users
  get "u/:username", to: "public#profile", constraints: { username: /[^\/]+/}, as: "profile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "search", to: "records#search", as: "search"
  # get "business", to: "records#business", as: "business"

  get "terms", to: "records#terms", as: "terms"
  get "privacy", to: "records#privacy", as: "privacy"
  get "websiteprivacypage", to: "records#websiteprivacy", as: "websiteprivacy"
  get "home", to: "records#home", as: "home"
  get "vaccines", to: "records#vaccines", as: "vaccines"

  delete 'records/:id/picture', to: 'records#destroy_picture', as: 'picdestroy'

  get "users", to: "users#index", as:"users"
  get "business", to: "records#business", as: "business"


  resources :communities do
    resources :posts
  end



  resources :subscriptions
  resources :comments, only: [:create]
  post "post/vote", to: "votes#create"
  post "comment/votecomment", to: "votecomments#create"




  # authenticated :user do
  #   root 'records#new', as: :authenticated_poop
  # end
  authenticated :user do
    root :to => 'records#routes'
  end
  root to: 'records#home'
  # root to: 'records#home'
  get "public", to: "public#index", as: "public"
end

app/models/community.rb
class Community < ApplicationRecord
    belongs_to :user
    has_many :posts
    has_many :subscriptions
    has_many :subscribers, through: :subscriptions, source: :user
    validates_presence_of :name, :rules
    validates_length_of :name, :maximum => 50
    validates_length_of :summary, :maximum => 75
    validates_length_of :rules, :maximum => 75


end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
before_action :authenticate_user!, except: [ :index, :show ]
before_action :set_community, only: [ :show ]

    def index
        @communities = Community.all
    end

    def show
        @posts = @community.posts.sort_by{|p| p.score}.reverse
        @subscriber_count = @community.subscribers.count
        @is_subscribed = user_signed_in? ? Subscription.check_if_user_signed_in(@community, current_user) : false
        @subscription = Subscription.new
    end

    def new
        @community = Community.new
    end

    def create
        @community = Community.new(community_params)

        @community.user_id = current_user.id
        if @community.save
            redirect_to communities_path
        else
            render :new
        end
    end

    private

    def set_community
        @community = Community.includes(:posts).find(params[:id])
    end

    def community_params
        params.require(:community).permit(:name, :rules, :summary)
    end
end

app/views/communities/_form.html.erb
<div class="row">
    <div class="col-sm-6">
      *All fields should be less than 50 characters
        <%= form_for @community do |form| %>
            <div class="form-group">
                <%= label_tag :name %>
                <%= form.text_field :name, class: "form-control"%>
            </div>



            <div class="form-group">
                <%= label_tag :summary %>
                <%= form.text_field :summary, class: "form-control"%>
            </div>

            <div class="form-group">
                <%= label_tag :rules %>
                <%= form.text_area :rules, class: "form-control"%>
            </div>

            <%= form.submit "Submit", class:"btn btn-primary"%>
        <% end %>
    </div>
</div>

app/views/communities/_subscribe.html.erb
<%= form_for @subscription do |f| %>
    <%= f.hidden_field :community_id, value: community_id %>
    <%= f.submit "Join Community", class: "btn btn-success text-uppercase float-right commentbuttondown commleft2"  %>
<% end %>

app/views/communities/index.html.erb
<div class = "commleft">
<% if user_signed_in? %>
<div class="float-right">
    <%= link_to "Create New Community", new_community_path, class: "btn btn-primary mt-4 buttondown commbutton" %>
</div>
<% end %>

Communities:
<% if @communities.size > 0 %>
<% @communities.each do |community| %>

<div class="cards cards1 movecardleft">

<h3 class = "commname"><%= link_to community.name, community %></h3>
<span class = "fontsmall"> Summary: <%= simple_format community.summary %> </span>
<span class = "fontsmall"> Rules: <%= simple_format community.rules %> </span>
</div>

<% end %>
<% else %>
    <p>No communities to display</p>
<% end %>
</div>

<div class = "twobuttons upcoming"><%= link_to "Popular Posts", public_path, class: "btn btn-primary mt-4 twobuttons topcommbutton"%> </div>

app/views/communities/new.html.erb
<div class = "newleft">
<h2 > New Community </h2>

<%= render partial: "form" %>
</div>

app/views/communities/show.html.erb
<div class="row mb-4">
    <div class="col-sm-8">
        <h3 class = "name"><%= @community.name %></h3>
    </div>
    <div class="col-sm-4">
        <% if @is_subscribed %>
            <%= link_to "Create New Post", new_community_post_path(@community),  class: "btn btn-primary float-right buttonpost"  %>
        <% else %>
            <%= render partial: "communities/subscribe", locals: { community_id: @community.id } %>
        <% end %>
    </div>
</div>


<div class="row">
    <div class="col-sm-8">

        <%= render partial: "posts/list", locals: { posts: @posts } %>

    </div>
    <div class="col-sm-4" style = "padding-left: 27px;">
        <div class="card p-3">
        <p class="h5 commcolor">About this community:</p>
            <p class="mt-2 commcolor summaryfont"><%= @community.summary %></p>
        </div>

        <p class = "count"><%= pluralize @subscriber_count, "member" %> </p>
        <small class = "rules">
            Rules: <%= simple_format @community.rules %>
        </small>
    </div>
</div>


<div class = "twobuttons">
 <div><%= link_to "View all Communities", communities_path, class: "btn btn-primary mt-4"%> </div>

<div class = "topcommbutton"><%= link_to "Popular Posts & Up and Coming Communities", public_path, class: "btn btn-primary mt-4 commbuttonwidth"%> </div>
</div>